USE rml;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS rml.Student_Sport;
DROP TABLE IF EXISTS rml.Sport;
DROP TABLE IF EXISTS rml.Student;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE Sport (ID INTEGER, Description VARCHAR(200));
INSERT INTO Sport values ('110','Tennis');
INSERT INTO Sport values ('111','Football');
INSERT INTO Sport values ('112','Formula1');
CREATE TABLE Student (ID INTEGER, FirstName VARCHAR(200), LastName VARCHAR(200));
INSERT INTO Student values ('10','Venus','Williams');
INSERT INTO Student values ('11','Fernando','Alonso');
INSERT INTO Student values ('12','David','Villa');
CREATE TABLE Student_Sport (ID_Student INTEGER, ID_Sport INTEGER);
INSERT INTO Student_Sport values ('10', '110');
INSERT INTO student_sport values ('11','111');
INSERT INTO Student_Sport values ('11','112');
INSERT INTO Student_Sport values ('12','111');
